package com.project.shopping.domain;

import java.io.Serializable;

public class PtShopcart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.ShopCartId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private Integer shopcartid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.shopId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private Integer shopid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.shopname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private String shopname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.shopnum
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private Integer shopnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.userid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.username
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.businessname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private String businessname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pt_shopcart.businessid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private Integer businessid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.ShopCartId
     *
     * @return the value of pt_shopcart.ShopCartId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public Integer getShopcartid() {
        return shopcartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.ShopCartId
     *
     * @param shopcartid the value for pt_shopcart.ShopCartId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setShopcartid(Integer shopcartid) {
        this.shopcartid = shopcartid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.shopId
     *
     * @return the value of pt_shopcart.shopId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.shopId
     *
     * @param shopid the value for pt_shopcart.shopId
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.shopname
     *
     * @return the value of pt_shopcart.shopname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public String getShopname() {
        return shopname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.shopname
     *
     * @param shopname the value for pt_shopcart.shopname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setShopname(String shopname) {
        this.shopname = shopname == null ? null : shopname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.shopnum
     *
     * @return the value of pt_shopcart.shopnum
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public Integer getShopnum() {
        return shopnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.shopnum
     *
     * @param shopnum the value for pt_shopcart.shopnum
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setShopnum(Integer shopnum) {
        this.shopnum = shopnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.userid
     *
     * @return the value of pt_shopcart.userid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.userid
     *
     * @param userid the value for pt_shopcart.userid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.username
     *
     * @return the value of pt_shopcart.username
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.username
     *
     * @param username the value for pt_shopcart.username
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.businessname
     *
     * @return the value of pt_shopcart.businessname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public String getBusinessname() {
        return businessname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.businessname
     *
     * @param businessname the value for pt_shopcart.businessname
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setBusinessname(String businessname) {
        this.businessname = businessname == null ? null : businessname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pt_shopcart.businessid
     *
     * @return the value of pt_shopcart.businessid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public Integer getBusinessid() {
        return businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pt_shopcart.businessid
     *
     * @param businessid the value for pt_shopcart.businessid
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    public void setBusinessid(Integer businessid) {
        this.businessid = businessid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", shopcartid=").append(shopcartid);
        sb.append(", shopid=").append(shopid);
        sb.append(", shopname=").append(shopname);
        sb.append(", shopnum=").append(shopnum);
        sb.append(", userid=").append(userid);
        sb.append(", username=").append(username);
        sb.append(", businessname=").append(businessname);
        sb.append(", businessid=").append(businessid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PtShopcart other = (PtShopcart) that;
        return (this.getShopcartid() == null ? other.getShopcartid() == null : this.getShopcartid().equals(other.getShopcartid()))
            && (this.getShopid() == null ? other.getShopid() == null : this.getShopid().equals(other.getShopid()))
            && (this.getShopname() == null ? other.getShopname() == null : this.getShopname().equals(other.getShopname()))
            && (this.getShopnum() == null ? other.getShopnum() == null : this.getShopnum().equals(other.getShopnum()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getBusinessname() == null ? other.getBusinessname() == null : this.getBusinessname().equals(other.getBusinessname()))
            && (this.getBusinessid() == null ? other.getBusinessid() == null : this.getBusinessid().equals(other.getBusinessid()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getShopcartid() == null) ? 0 : getShopcartid().hashCode());
        result = prime * result + ((getShopid() == null) ? 0 : getShopid().hashCode());
        result = prime * result + ((getShopname() == null) ? 0 : getShopname().hashCode());
        result = prime * result + ((getShopnum() == null) ? 0 : getShopnum().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getBusinessname() == null) ? 0 : getBusinessname().hashCode());
        result = prime * result + ((getBusinessid() == null) ? 0 : getBusinessid().hashCode());
        return result;
    }
}