package com.project.shopping.mapper;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;

import com.project.shopping.domain.PtShopcart;

@Mapper
public interface PtShopcartMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    int deleteByPrimaryKey(Integer shopcartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generatoed Sun Apr 12 09:51:47 CST 2020
     */
    int insert(PtShopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    int insertSelective(PtShopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    PtShopcart selectByPrimaryKey(Integer shopcartid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    int updateByPrimaryKeySelective(PtShopcart record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pt_shopcart
     *
     * @mbg.generated Sun Apr 12 09:51:47 CST 2020
     */
    int updateByPrimaryKey(PtShopcart record);

	List<PtShopcart> selectAllShopcart(Integer userId);
	List<PtShopcart> selectShopcartBs(Integer userId);

	PtShopcart selectByPs(PtShopcart ps);
}